CREATE TABLE migration_test (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    message VARCHAR(100) NOT NULL,
    created_at DATETIME(3)
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (id)
);